services:

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=polku_db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    

  web:
    build: .
    command: uvicorn polku_backend.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - PYTHONPATH=/usr/src/app
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/polkudb
    depends_on:
      db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # Email para acceso a PGAdmin
      PGADMIN_DEFAULT_PASSWORD: admin          # Contraseña para acceso a PGAdmin
    ports:
      - "5050:80" # Mapea el puerto 80 del contenedor al 5050 en el host
    depends_on:
      - db

volumes:
  db_data: {}

  